// Probe: what does it cost to ask "is my sync root still the right mount?"
//
// The delta thread asks this once per round today, and a round that applies
// 147,540 changes takes minutes -- so the answer is stale for almost the whole
// pass. Moving the question inside the apply loop makes it per item, and the
// obvious objection is cost. This measures it, because the two candidates are
// not the same order of magnitude and the argument should not be conducted on
// intuition.
//
//   1. `mount::is_mount_point` -- read /proc/self/mountinfo, scan for the path.
//      A few kilobytes, generated by the kernel on every open, then parsed.
//   2. `selfcheck::MountIdentity` -- one statx for STATX_MNT_ID_UNIQUE.
//
// The C parse here is a *lower bound* on what the Rust costs: `is_mount_point`
// does `read_to_string`, `lines()`, and allocates a `String` per candidate line
// through `unescape`. Nothing below allocates. So if C already says the gap is
// large, Rust's gap is larger.
//
// There is a correctness difference too, and it outlives the cost one: the
// mountinfo check asks whether *a* mount is at the path, and the statx check
// asks whether it is *the same* mount. probes/mntid.c already measured that an
// unmount and remount hands the small id straight back while the unique id
// changes; a path check cannot tell those apart at all.
//
//   cc -O2 -o /tmp/mountcheck_cost probes/mountcheck_cost.c
//   /tmp/mountcheck_cost <path> [iterations]
#define _GNU_SOURCE
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <time.h>
#include <unistd.h>

#ifndef STATX_MNT_ID_UNIQUE
#define STATX_MNT_ID_UNIQUE 0x00004000U
#endif

static double now_us(void) {
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return t.tv_sec * 1e6 + t.tv_nsec / 1e3;
}

// The mountinfo half, shaped like `mount::is_mount_point`: read the whole file,
// then look at field 4 of every line for an exact match on the path.
//
// The read *loops*, and that is not defensive coding. `/proc/self/mountinfo` is
// a seq_file: one `read(2)` with a 256 KiB buffer returned 4016 of this
// machine's 4394 bytes and stopped -- 33 of 35 mounts, silently, with a short
// count that looks exactly like end of file. The first version of this probe
// read once and reported the sync mount ABSENT while `grep` found it on line 35.
// Rust's `read_to_string` already loops, so `mount::is_mount_point` never had
// this bug; a C probe measuring "the same thing" would have been measuring a
// truncated parse and calling it cheaper.
static int by_mountinfo(const char *path, size_t *bytes, int *lines) {
    static char buf[256 * 1024];
    int fd = open("/proc/self/mountinfo", O_RDONLY);
    if (fd < 0) return -1;
    ssize_t n = 0, total = 0;
    while ((n = read(fd, buf + total, sizeof buf - 1 - total)) > 0) total += n;
    close(fd);
    if (n < 0) return -1;
    buf[total] = 0;
    *bytes = (size_t)total;

    int found = 0, nl = 0;
    for (char *line = buf; line && *line;) {
        char *end = strchr(line, '\n');
        if (end) *end = 0;
        nl++;
        // `id parent major:minor root point ...` -- field 4, zero-based.
        char *p = line;
        for (int f = 0; f < 4 && p; f++) {
            p = strchr(p, ' ');
            if (p) p++;
        }
        if (p) {
            char *sp = strchr(p, ' ');
            size_t len = sp ? (size_t)(sp - p) : strlen(p);
            if (len == strlen(path) && memcmp(p, path, len) == 0) found = 1;
        }
        if (!end) break;
        *end = '\n';
        line = end + 1;
    }
    *lines = nl;
    return found;
}

static int by_statx(const char *path, unsigned long long *id) {
    struct statx sx;
    memset(&sx, 0, sizeof sx);
    if (syscall(SYS_statx, AT_FDCWD, path, 0, STATX_MNT_ID_UNIQUE, &sx) != 0) return -1;
    if (!(sx.stx_mask & STATX_MNT_ID_UNIQUE)) return -1;
    *id = sx.stx_mnt_id;
    return 0;
}

int main(int argc, char **argv) {
    const char *path = argc > 1 ? argv[1] : "/";
    long iters = argc > 2 ? atol(argv[2]) : 20000;

    size_t bytes = 0;
    int lines = 0, found = by_mountinfo(path, &bytes, &lines);
    unsigned long long id = 0;
    int have_id = by_statx(path, &id) == 0;

    printf("path: %s\n", path);
    printf("  mountinfo: %zu bytes, %d lines, path %s\n", bytes, lines,
           found ? "present" : "ABSENT");
    if (have_id) printf("  unique mount id: %llu\n", id);
    else printf("  unique mount id: unavailable\n");

    double t0 = now_us();
    for (long i = 0; i < iters; i++) by_mountinfo(path, &bytes, &lines);
    double mi = (now_us() - t0) / iters;

    t0 = now_us();
    for (long i = 0; i < iters; i++) by_statx(path, &id);
    double sx = (now_us() - t0) / iters;

    printf("\nper call, mean of %ld:\n", iters);
    printf("  mountinfo read+parse: %8.2f us\n", mi);
    printf("  statx unique mnt id:  %8.2f us   (%.0fx cheaper)\n", sx, mi / sx);

    // The number that decides the argument: the pass that failed had 147,540
    // items in it.
    printf("\nover a 147,540-item pass:\n");
    printf("  mountinfo per item: %8.2f s\n", mi * 147540 / 1e6);
    printf("  statx per item:     %8.2f s\n", sx * 147540 / 1e6);
    return 0;
}
